/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "packet.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Meta, Meta, AUTO)


PB_BIND(SensorField, SensorField, AUTO)


PB_BIND(Packet, Packet, AUTO)





